### ISSUE TITLE
Publishing on MELPA

### ISSUE THREAD

**Issue by mostafah** [ianpan870102/acme-emacs-theme#3]
I really like this theme. It would be nice to have it on MELPA too.

**Comment by ianyepan** [comment]
Hi @mostafah ! Thanks for the kind words, I am indeed going through the process of merging it on MELPA
https://github.com/melpa/melpa/pull/6997

**Comment by ianyepan** [comment]
@mostafah Hi there! The PR is merged, you may now install acme-theme like so:

```emacs-lisp
(use-package acme-theme
  :config
  (load-theme 'acme t))
```

Enjoy my friend!
